version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - flat-earth-network

networks:
  flat-earth-network:
    driver: bridge 